BUG: Add method for vector of bool changed
This addresses the following run-time error with the FlipImageFilter:

exec('self.filter.Set{0}(coords)'.format(name))

File "<string>", line 1, in <module>

File
"/home/yliu/Imaging/slicer/Slicer-4.4.0-2015-05-20-linux-amd64/lib/Python/lib/python2.7/site-packages/SimpleITK-0.9.0-py2.7-linux-x86_64.egg/SimpleITK/SimpleITK.py",
line 43400, in SetFlipAxes

return _SimpleITK.FlipImageFilter_SetFlipAxes(self, *args, **kwargs)

TypeError: in method 'FlipImageFilter_SetFlipAxes', argument 2 of type
'std::vector< bool,std::allocator< bool > > const &'

The assumed explaination for this is that SWIG changed it's behavior
with regaurds to implicit conversion for a tuple of int to a tuple of
bool.

Thanks to  Yanling Liu <liuy5@mail.nih.gov> for reporting the issue.